import type { NextPage } from 'next'
import Head from 'next/head'
import { Flex, Box, Text, Input, Button, InputGroup, InputRightElement } from '@chakra-ui/react'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        justify='center'
        alignItems='center'
        mt='16'
      >
        <Box
          w={550}
          backgroundColor='gray.800'
          color='white'
          px='8'
          py='8'
          rounded='2xl'
        >
          <Text 
            fontSize='3xl'
            fontWeight='bold'
            mb='4'
          >
            TASK
          </Text>

          <InputGroup
            size='md'
            w='auto'
          >
            <Input 
              placeholder='Digite uma tarefa' 
              size='md'
              backgroundColor='white'
              color='black'
            />
            <InputRightElement
              w='5.5rem'
            >
              <Button 
                colorScheme='teal' 
                variant='solid'
              >
                Adicionar
              </Button>
            </InputRightElement>
          </InputGroup>

        </Box>
      </Flex>

    </div>
  )
}

export default Home
